export * from './classrooms.module';
export * from './courses.module';
export * from './enrollments.module';
export * from './grades.module';
export * from './professors.module';
export * from './students.module';
export * from './subjects.module';
export * from '../../application/auth/auth.module';
export * from '../../infrastructure/config/global-config.module';
