export const errorCodes = {
    UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
    FOREIGN_KEY_CONSTRAINT_VIOLATION: 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
    NOT_NULL_CONSTRAINT_VIOLATION: 'NOT_NULL_CONSTRAINT_VIOLATION',
    CHECK_CONSTRAINT_VIOLATION: 'CHECK_CONSTRAINT_VIOLATION',
    EXCLUSION_CONSTRAINT_VIOLATION: 'EXCLUSION_CONSTRAINT_VIOLATION',
    SYNTAX_ERROR: 'SYNTAX_ERROR',
    INVALID_TEXT_REPRESENTATION: 'INVALID_TEXT_REPRESENTATION',
};
